function raw_data = P1_ImportFile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  ALICEGX010290120HZ = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  ALICEGX010290120HZ = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  AliceGX010290120Hz = importfile("D:\AppData\GitHub\SLIP_Quadruped\P3_Asymmetrical_Gaits_and_Animal_Data\Sled_Dog_Data\Alice_GX010290_120_Hz.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 03-Jun-2024 23:13:30

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 16);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "ax", "ay", "az", "gx", "gy", "gz", "load", "offset", "error", "force", "frame", "LF", "RF", "LH", "RH"];
opts.SelectedVariableNames = ["ax", "ay", "az", "gx", "gy", "gz", "load", "offset", "error", "force", "frame", "LF", "RF", "LH", "RH"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Var1", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Var1", "EmptyFieldRule", "auto");

% Import the data
raw_data = readtable(filename, opts);

end